CREATE SEQUENCE IF NOT EXISTS store_id_seq
 INCREMENT 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 START 1
 CACHE 1;

CREATE TABLE IF NOT EXISTS store (
  store_id bigint NOT NULL PRIMARY KEY DEFAULT nextval('store_id_seq'),
  name varchar(100) NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);