CREATE SEQUENCE IF NOT EXISTS payment_id_seq
 INCREMENT 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 START 1
 CACHE 1;

CREATE TABLE IF NOT EXISTS payment (
  payment_id bigint NOT NULL PRIMARY KEY DEFAULT nextval('payment_id_seq'),
  order_id bigint NOT NULL,
  payment_auth varchar(255) NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);